### ISSUE TITLE
Optionally pass an own implementation of `Symbol`

### ISSUE THREAD

**Issue by tomek-he-him** [seangenabe/symbol-enum#2]
In my experience relying on global polyfills is [not a good thing](https://github.com/sindresorhus/object-assign/issues/10#issuecomment-65065859). It would be great if it were possible to pass a custom implementation of `Symbol` optionally.

``` js
// We’re in ES 2015+ – `Symbol` is there natively:
import Enum from 'symbol-enum/module';

// We’re in today’s JS – transpiled or not:
const Enum = require('symbol-enum')(
  {Symbol: require('es6-symbol')}
);
```

We’ve actually already had a go at an API like this and it’s proving quite well, although it’s still a work in progress: https://github.com/stoeffel/chickencurry/commit/b0dd566#commitcomment-12418387. So I’d be happy to help with this as soon as the tests are up and running ( #1 ).

**Comment by tomek-he-him** [comment]
By the way, this wouldn’t have to be a breaking change.

**Comment by seangenabe** [comment]
I have decided to depend on `babel-runtime` for this module, so this won't be necessary. However, I can still add something like that if you like.

**Comment by tomek-he-him** [comment]
If you already depend on the runtime, this wouldn’t make sense.

I personally prefer more lightweight solutions. _core-js_ used by _babel-runtime_ weighs over 20 KB minzipped (about ⅔ as much as _jquery_). That’s a lot for a simple thing which could be solved (if someone wished) without any polyfill. For example:

``` js
const Enum = require('symbol-enum')(
  {Symbol: (label) => ({toString: () => `@@${label}`})}
);
```

**Comment by tomek-he-him** [comment]
Feel free to close the issue if you don’t want to change it though.

**Comment by seangenabe** [comment]
What I'm aiming for is backwards compatibility with node.js 0.10 and maybe lower, etc., so any sort of ES2015 syntax would, sadly, fail in those environments. I do agree about using smaller libraries but I'm kinda into the babel thing now, so.

Also, including different polyfills from different sources might be bad in one way or another, further increasing library bloat. I'd like to avoid that by using something popular so it's likely also included in other libraries that use it.

Also, I've seen that `core-js` is extremely modular, so even though we're increasing the download size of the library, it's not like it'll be loaded all at once. Only the required polyfills will ever be loaded.

Anyway, closing.
